spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.105:1521/DEV
    username: HR
    password: HR
  jpa:
    properties:
      hibernate:
           format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      
logging:
  level:
    '[org.hibernate.type.decriptor]': trace 