server:
  port: 8780
  
eureka:  
  client: 
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8780/eureka

management:
  endpoints: 
    web:
      exposure:
        include:
        - "*"