spring:
  application:
    name: config-client
  config:
    import: configserver:http://localhost:8888
    
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"      