spring:
  application:
    name: trip-detail-service

  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 4444
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
