server:
  port: 8888
  
spring:
  cloud:
    config:  
      server:
        git:
          uri: https://github.com/venkateshvenki1122/cloud-config.git
          search-paths:
          - '{application}'

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"







